import urllib.request
import json

import os

# Get NVIDIA API Key from environment variable
NVIDIA_API_KEY = os.environ.get("NVIDIA_API_KEY", "")

def generate_rubric_batch_(question, initial_rubric_text, total_marks):
    url = "https://integrate.api.nvidia.com/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {NVIDIA_API_KEY}",
        "Content-Type": "application/json"
    }
    
    prompt = f"""You are an expert educator creating grading rubrics.
I have a question and a preliminary grading rubric generated by a small AI model.
The small model often generates incomplete rubrics with too few criteria (usually only 1 or 2).
Your task is to refine, expand, and correct the rubric to have exactly 3 distinct, high-quality criteria.

Question: {question}
Preliminary Rubric: {initial_rubric_text}
Total Marks Available: {total_marks if total_marks else 'Not specified'}

Please provide the finalized rubric.
FORMAT REQUIREMENT:
You must format your output EXACTLY as a numbered list where each point optionally ends with the marks in brackets, like "[X marks]".
CRITICAL INSTRUCTION: Do NOT write long descriptive sentences. Each criterion MUST be a short, concise phrase (maximum 3-5 words) representing the core concept.
Example:
1. Greedy Approach Logic [4 marks]
2. Index Handling [3 marks]
3. Complexity Analysis [3 marks]

Do not include any intro or outro text. Only output the numbered list.
"""
    payload = {
        "model": "meta/llama-3.1-8b-instruct",
        "messages": [
            {"role": "user", "content": prompt}
        ],
        "temperature": 0.3,
        "max_tokens": 512
    }
    
    try:
        req = urllib.request.Request(url, data=json.dumps(payload).encode('utf-8'), headers=headers, method='POST')
        with urllib.request.urlopen(req) as response:
            result = json.loads(response.read().decode('utf-8'))
            return result['choices'][0]['message']['content'].strip()
    except Exception as e:
        print(f"LLaMA API error: {e}")
        return initial_rubric_text # Fallback to initial if API fails
